export const translationsContacts = {
    ru: {
      title: 'Контакты',
      subtitle: 'Для официальных запросов и предложений о сотрудничестве',
      contactInfo: 'Контактная информация',
      email: 'Электронная почта',
      emailFor: 'Для официальных запросов',
      phone: 'Телефон',
      phoneFor: 'Для экстренных вопросов',
      address: 'Адрес',
      addressFor: 'Официальное представительство',
      workHours: 'Часы приема',
      monThu: 'Понедельник — Четверг',
      fri: 'Пятница',
      appointment: 'Предварительная запись',
      required: 'Обязательна',
      formTitle: 'Форма обратной связи',
      fullName: 'Ваше полное имя *',
      emailPlaceholder: 'Иванов Иван Иванович',
      yourEmail: 'Электронная почта *',
      emailInputPlaceholder: 'ivanov@example.com',
      organization: 'Организация',
      orgPlaceholder: 'Название организации',
      subject: 'Тема сообщения *',
      selectSubject: 'Выберите тему',
      cooperation: 'Предложение о сотрудничестве',
      invitation: 'Приглашение на мероприятие',
      consultation: 'Запрос на консультацию',
      other: 'Другое',
      message: 'Сообщение *',
      messagePlaceholder: 'Ваше сообщение...',
      send: 'Отправить сообщение',
      requiredFields: '* Обязательные поля для заполнения',
      info: 'Обработка запросов осуществляется в соответствии с регламентом. Конфиденциальность переписки гарантируется.',
      successTitle: 'Сообщение отправлено',
      successText: 'Ваше сообщение успешно отправлено. Я свяжусь с вами в ближайшее время.',
      close: 'Закрыть',
      sending: 'Отправка...'
    },
    en: {
      title: 'Contacts',
      subtitle: 'For official inquiries and partnership proposals',
      contactInfo: 'Contact Information',
      email: 'Email',
      emailFor: 'For official inquiries',
      phone: 'Phone',
      phoneFor: 'For urgent matters',
      address: 'Address',
      addressFor: 'Official representation',
      workHours: 'Working Hours',
      monThu: 'Monday — Thursday',
      fri: 'Friday',
      appointment: 'Appointment',
      required: 'Required',
      formTitle: 'Contact Form',
      fullName: 'Your Full Name *',
      emailPlaceholder: 'John Doe',
      yourEmail: 'Email Address *',
      emailInputPlaceholder: 'john@example.com',
      organization: 'Organization',
      orgPlaceholder: 'Organization name',
      subject: 'Message Subject *',
      selectSubject: 'Select a subject',
      cooperation: 'Partnership Proposal',
      invitation: 'Event Invitation',
      consultation: 'Consultation Request',
      other: 'Other',
      message: 'Message *',
      messagePlaceholder: 'Your message...',
      send: 'Send Message',
      requiredFields: '* Required fields',
      info: 'Requests are processed in accordance with regulations. Confidentiality of correspondence is guaranteed.',
      successTitle: 'Message Sent',
      successText: 'Your message has been successfully sent. I will contact you shortly.',
      close: 'Close',
      sending: 'Sending...'
    },
    fr: {
      title: 'Contacts',
      subtitle: 'Pour les demandes officielles et les propositions de partenariat',
      contactInfo: 'Informations de contact',
      email: 'Email',
      emailFor: 'Pour les demandes officielles',
      phone: 'Téléphone',
      phoneFor: 'Pour les questions urgentes',
      address: 'Adresse',
      addressFor: 'Représentation officielle',
      workHours: 'Heures de réception',
      monThu: 'Lundi — Jeudi',
      fri: 'Vendredi',
      appointment: 'Rendez-vous',
      required: 'Obligatoire',
      formTitle: 'Formulaire de contact',
      fullName: 'Votre nom complet *',
      emailPlaceholder: 'Jean Dupont',
      yourEmail: 'Adresse email *',
      emailInputPlaceholder: 'jean@exemple.com',
      organization: 'Organisation',
      orgPlaceholder: 'Nom de l\'organisation',
      subject: 'Sujet du message *',
      selectSubject: 'Sélectionnez un sujet',
      cooperation: 'Proposition de partenariat',
      invitation: 'Invitation à un événement',
      consultation: 'Demande de consultation',
      other: 'Autre',
      message: 'Message *',
      messagePlaceholder: 'Votre message...',
      send: 'Envoyer le message',
      requiredFields: '* Champs obligatoires',
      info: 'Les demandes sont traitées conformément aux règlements. La confidentialité de la correspondance est garantie.',
      successTitle: 'Message envoyé',
      successText: 'Votre message a été envoyé avec succès. Je vous contacterai sous peu.',
      close: 'Fermer',
      sending: 'Envoi en cours...'
    }
  };

	const currentYear = new Date().getFullYear();

	export  const translationsFooter = {
    ru: {
      name: 'Александр Петров',
      title: 'Госслужащий международного уровня',
      description: 'Официальный представитель на международной арене, специалист по дипломатическим отношениям и стратегическому планированию.',
      sectionsTitle: 'Разделы',
      about: 'Обо мне',
      experience: 'Опыт работы',
      expertise: 'Экспертиза',
      recognition: 'Признание',
      contactsTitle: 'Контакты',
      email: 'a.petrov@govdiplomat.ru',
      phone: '+7 (XXX) XXX-XX-XX',
      address: 'Москва, Смоленская-Сенная пл., 32/34',
      representationTitle: 'Международное представительство',
      languages: {
        ru: 'РУС',
        en: 'АНГ',
        fr: 'ФРА',
      },
      copyright: `© ${currentYear} Александр Петров. Официальный сайт.`,
      legalInfo: 'Информация представлена в соответствии с требованиями законодательства. Все права защищены.'
    },
    en: {
      name: 'Alexander Petrov',
      title: 'International Civil Servant',
      description: 'Official representative on the international stage, specialist in diplomatic relations and strategic planning.',
      sectionsTitle: 'Sections',
      about: 'About Me',
      experience: 'Experience',
      expertise: 'Expertise',
      recognition: 'Recognition',
      contactsTitle: 'Contacts',
      email: 'a.petrov@govdiplomat.ru',
      phone: '+7 (XXX) XXX-XX-XX',
      address: 'Moscow, Smolenskaya-Sennaya sq., 32/34',
      representationTitle: 'International Representation',
      languages: {
        ru: 'RUS',
        en: 'ENG',
        fr: 'FRA',
      },
      copyright: `© ${currentYear} Alexander Petrov. Official Website.`,
      legalInfo: 'Information is presented in accordance with legal requirements. All rights reserved.'
    },
    fr: {
      name: 'Alexandre Petrov',
      title: 'Fonctionnaire international',
      description: 'Représentant officiel sur la scène internationale, spécialiste des relations diplomatiques et de la planification stratégique.',
      sectionsTitle: 'Sections',
      about: 'À propos',
      experience: 'Expérience',
      expertise: 'Expertise',
      recognition: 'Reconnaissance',
      contactsTitle: 'Contacts',
      email: 'a.petrov@govdiplomat.ru',
      phone: '+7 (XXX) XXX-XX-XX',
      address: 'Moscou, Place Smolenskaya-Sennaya, 32/34',
      representationTitle: 'Représentation internationale',
      languages: {
        ru: 'RUS',
        en: 'ANG',
        fr: 'FRA',
      },
      copyright: `© ${currentYear} Alexandre Petrov. Site officiel.`,
      legalInfo: 'Les informations sont présentées conformément aux exigences légales. Tous droits réservés.'
    }
  };